apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: seldon-model
spec:
  name: test-deployment
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - name: classifier
          image: msmetko/test_model:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: 500Mi
            limits:
              nvidia.com/gpu: 1
          runtime: nvidia
        imagePullSecrets:
        - name: regcred
    name: example
    replicas: 1
    graph:
      name: classifier
      endpoint:
        type: REST
      # TRANSFORMER transforms its input and forwards the result to it's children
      # type: TRANSFORMER
      type: MODEL
      children: []
#        - name: classifier
#          endpoint:
#            type: REST
#          # OUTPUT_TRANSFORMER forwards the input to its children and transforms _their_ output
#          type: OUTPUT_TRANSFORMER
#          children:
#            - name: classifier
#              endpoint:
#                type: REST
#              type: MODEL
#              children: []

